-- 1. Pull total number of orders that were completed on 18th March 2023
--      with the first name ‘John’ and last name 'Doe'
SELECT COUNT(*) FROM SALES WHERE DATE='2023-03-18'
SELECT COUNT(*) FROM SALES S
JOIN CUSTOMERS C ON S.CUSTOMER_ID = C.CUSTOMER_ID
WHERE C.FIRST_NAME = 'John' AND C.LAST_NAME = ' Doe'

-- 2. Pull total number of customers that purchased in January 2023
--      and the average amount spend per customer
SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, AVG(REVENUE) AS AVG_COST
FROM CUSTOMERS C JOIN SALES S ON C.CUSTOMER_ID=S.CUSTOMER_ID
WHERE DATE BETWEEN '2023-03-01' AND '2023-03-31'
GROUP BY C.CUSTOMER_ID;

-- 3. Pull the departments that generated less than $600 in 2022
SELECT I.DEPARTMENT FROM ITEMS I
JOIN SALES S ON S.ITEM_ID=I.ITEM_ID
WHERE DATE BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY I.DEPARTMENT
HAVING SUM(REVENUE)>600;

-- 4. What is the most and least revenue we have generated by an order
SELECT MAX(REVENUE) AS MAX_REVENUE,MIN(REVENUE) AS MIN_REVENUE
FROM SALES;

-- 5. What were the orders that were purchased in our most lucrative order
SELECT * FROM SALES
WHERE REVENUE=(SELECT MAX(REVENUE) FROM SALES);
